### PR TITLE
OpenTelemetry 0.24 support

### PR DESCRIPTION
**Pull request by mladedav**
Updates and hopefully fixes #168 

Building doesn't seem to work with `--all-features` but looking at it I don't think it ever worked with `deprecated_attributes`.

Feel free to just take the code and put it into the original PR or merge this.

### CODE REVIEW

**Review by eopb — APPROVED** [review]
Thank you for your PR, LGTM 🙌

**Comment by SimenB** [comment]
Can this get a release? 🙂

**Comment by mladedav** [comment]
@eopb Sorry to bump this, but can this get a (patch) release? This is hopefully the last thing we're waiting on to be able to update OpenTelemetry and move on to `http@1.0`.

Or are there some breaking changes in master and this waits for some other changes?

**Comment by eopb** [comment]
There's nothing blocking the next release. I just haven't had an opportunity to cut it yet. I'll make sure something happens in the coming days 👍

**Comment by eopb** [comment]
This has now been released 🎉 

https://github.com/TrueLayer/reqwest-middleware/releases/tag/reqwest-tracing-v0.5.3

Sorry about the wait

**Pull request merged**
