### PR TITLE
Added version function to RequestBuilder impl

### PR DESCRIPTION
**Pull request by jeramyRR**
Addresses an issue where the Http version of a request cannot be changed when using reqwest_middleware.

### CODE REVIEW

**Review by conradludgate — APPROVED** [review]
Thanks!

**Comment by jeramyRR** [comment]
Fixed the build issue where `version` is not available for WASM32 versions of reqwest::RequestBuilder

**Review by conradludgate — APPROVED** [review]

**Comment by conradludgate** [comment]
What is the reason for closing this?

**Comment by jeramyRR** [comment]
Yeah I think I messed up.  Thought it had already merged.

**Review by conradludgate — APPROVED** [review]

**Comment by jeramyRR** [comment]
Is there a way to request an official release to cargo?

**Comment by conradludgate** [comment]
Sure, I'll release in a few minutes

**Comment by conradludgate** [comment]
0.2.2 released

**Comment by jeramyRR** [comment]
Thank you!

**Pull request merged**
