### PR TITLE
Add support for `opentelemetry` version `0.21`

### PR DESCRIPTION
**Pull request by jtescher**
Also adds corresponding `tracing-opentelemetry` version `0.22`

### CODE REVIEW

**Comment by ivan-brko** [comment]
Is there a plan to merge this PR and release a new version of the crate?

**Comment by matheus23** [comment]
cc @conradludgate (as he's not watching this repository at the moment) and @tl-rodrigo-gryzinski for completion's sake.
I hope the ping is fine, if that's unwelcome, please let me know!

**Comment by LukeMathWalker** [comment]
cc @eopb

**Review by eopb — APPROVED** [review]

**Comment by eopb** [comment]
Thank you for the ping Luca.

I'm sorry that this PR has taken so long to review. I've been having issues getting notifications for when pull requests are opened. The SSO security on `github.com/TrueLayer` prevents these notifications from going to my phone or email. I need to improve the setup so I stop missing things.

Today is a little busy so I won't be able to make a release. I will make sure a release gets cut this weekend.

@jtescher thank you for your PR

**Comment by matheus23** [comment]
Thank you and no worries, Ethan! :)

**Pull request merged**
