### PR TITLE
update to opentelemetry 0.17

### LINKED ISSUE #28: update reqwest-tracing to opentelemetry 0.17
opentelemetry 0.17 was released recently. tracing-opentelemetry has an [in progress issue](https://github.com/tokio-rs/tracing/issues/1857), it should be available soon

### PR DESCRIPTION
**Pull request by Geal**
fix #28 

not finished yet, we need to wait for the release of tracing-opentelemetry

### CODE REVIEW

**Comment by Geal** [comment]
apparently the audit fails due to the use of the chrono crate, but that comes from reqwest-retry, not reqwest-tracing

**Comment by tl-rodrigo-gryzinski** [comment]
@Geal  thanks for looking into it, We'll update the master branch to get audit passing, the PR looks good to me so we'll merge it afterwards

**Comment by Geal** [comment]
any news on that? I could send a PR for the audit as well

**Comment by tl-rodrigo-gryzinski** [comment]
@Geal thanks for the patience, if you can submit a PR for the audit failure that'd be great

**Comment by Geal** [comment]
Apparently we will need to wait for a chrono update, that dependency cannot be replaced because it is used in the public API of retry_policies 😕

**Comment by LukeMathWalker** [comment]
This change is unrelated to the audit failure, I'd suggest we merge it in regardless @tl-rodrigo-gryzinski .

**Comment by tl-rodrigo-gryzinski** [comment]
@LukeMathWalker fair enough, I'm merging. We'll need to sort out the audit to cut a release though

**Comment by Geal** [comment]
the audit failure is caused by chrono: https://github.com/TrueLayer/reqwest-middleware/runs/5094255371?check_suite_focus=true
That crate is imported in reqwest-retry through [retry-policies](https://crates.io/crates/retry-policies). Since it is not imported by reqwest-tracing and reqwest-middleware, a new version of reqwest-tracing could be published independently, no?

**Pull request merged**
