### PR TITLE
Capture URL as http.url

### PR DESCRIPTION
**Pull request by rbtcollins**
captures the request URL to the canonical attribute for this.

### CODE REVIEW

**Review by conradludgate — APPROVED** [review]

**Comment by LukeMathWalker** [comment]
^ This has a high chance of leaking PII/sensitive data into the logs since `http.url` includes query parameters.

**Comment by LukeMathWalker** [comment]
It was omitted on purpose in the first implementation @conradludgate

**Comment by conradludgate** [comment]
Yeah, we're going to publish this in a major version. @tl-rodrigo-gryzinski realised the same. We should consider having an easy opt-out, not sure the best approach for that just yet.

In an ideal world, REST APIs shouldn't have any PII in the path/query 😞

**Comment by tl-rodrigo-gryzinski** [comment]
Should we make this opt-in instead?

**Comment by LukeMathWalker** [comment]
I think it should be opt-in rather than opt-out - defaults should be as secure as possible and then the user can lower the barriers if they think it makes sense.

**Comment by conradludgate** [comment]
We've reverted this behaviour and introduced a `SpanBackendWithUrl` to compensate

**Pull request merged**
