### PR TITLE
feat: Support OTel 0.25 & 0.26

### PR DESCRIPTION
**Pull request by SimenB**
Note that https://github.com/open-telemetry/opentelemetry-rust/pull/2040 removed custom `writer` support from `opentelemetry-stdout`, so I didn't add that to the tests. Not sure what its purpose is since it only uses `std::io::sink()` anyways?

### CODE REVIEW

**Comment by cloneable** [comment]
Hi! Is this okay to be merged and released soon?

**Comment by SimenB** [comment]
Added support for 0.26 as well, now

**Comment by SimenB** [comment]
Ping @eopb 🙂

**Review by conradludgate — APPROVED** [review]

**Review by eopb — APPROVED** [review]

**Comment by SimenB** [comment]
Thanks for merging! Any chance for a release as well? 😀

**Pull request merged**
